name: CI

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: ruff check
        run: |
          apk update && apk upgrade --no-cache
          apk add ruff --no-cache
          ruff check evillimiter_ng
