name: mirror

on: [push]

jobs:
  mirror-to-codeberg:
    runs-on: ubuntu-latest
    name: codeberg-mirror
      steps:
        - uses: actions/checkout@v5
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'ssh://git@codeberg.org/KevinCrrl/evillimiter-ng.git'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
