name: Update PKGBUILD on Tag

on:
  push:
    tags:
      - '*'

jobs:
  update-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    permissions:
      contents: write

    steps:
      - name: Install git
        run: pacman -Sy --noconfirm git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante para tags
          persist-credentials: true

      - name: Update PKGBUILD version
        run: |
          pacman -Syu --noconfirm pacman-contrib python nvchecker wget devtools tar

          wget https://github.com/KevinCrrl/repo_bot/archive/refs/tags/1.tar.gz
          tar -xvf 1.tar.gz
          mv repo_bot-1/*.py .

          useradd -m build_user
          chown -R build_user:build_user .

          chmod -R 777 .

          cd "$GITHUB_WORKSPACE"

          su build_user -c "python main.py . log.txt -v"

          chown -R root:root .

      - name: Commit and Push changes
        working-directory: ${{ github.workspace }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add pkgbuild/PKGBUILD || true

          git commit -m "pkgbuild: bump PKGBUILD" || echo "No changes to commit"

          git push origin HEAD:main